# Aim : bingo card proposal for the movie "Jungle Cruise"
# Author : Emilio Bruna
c(
  "Quilla means: ________",
  "HistoryFail: 'Steamer to Porto Velho' ",
  "Leafcutter Ants",
  "HistoryFail: Metal Arrowhead",
  "Trope: Dwindling Party ('1 by 1 the jungle took us')",
  "BioFail: Coral Snake",
  " 'Could you ask the bee for coordinates?' ",
  " 'The Natives' ",
  " 'The Trees...the bugs...the jjnnggll' ",
  "BioFail: flock of macaws",
  "BioFail: Cockatoo",
  " HistoryFail: In 1916 plural of 'Real'='Reis' ",
  " 'They can smell fear' ",
  " 'My eyeballs are sweating' ",
  "Pink River Dolphins",
  "Capuchin Monkeys",
  "BioFail: 'Did you see these Heliconias?' ",
  " 'LagrÍmas de Cristal' ",
  " 'This God-Forsaken Endless Amazon!' ",
  "Bio(Semi)Fail: Poison Dart Frogs",
  "Piranha",
  "BioFail: Toucas at night",
  " 'You are deeply unpleasant.' ",
  "Fail(-ish): 'C'mon Buena Niña!' ",
  " 'You're the worst cat I've ever had' ",
  " 'Dead as a Dodo' ",
  "CultureFail: Masato",
  "Trope: Captured by Cannibals",
  "Trope: Inevitable Waterfall",
  "Trope: Blowdarts!",
  "Trope: Vine Swing",
  "Trope: Bold Explorer",
  "Trope: Evil Colonialist",
  "Trope: Native Guide",
  "Trope: Chief's Daughter",
  "Trope: Adventurer Outfit",
  "Trope: Panthera Awesome",
  "Trope: Snakes Are Sinister",
  "Trope: Temple of Doom",
  "Trope: 'Everything is Trying To Kill You' ",
  "Trope: This jungle is devouring our souls",
  "Trope: Jungle Drums",
  "Trope: 'We’re never making it out alive!' ",
  " '...this “booga-booga” nonsense' ",
  "Trope: Cannibal Tribe"
  )

# ('They’re the ones that like to eat you and wear your eyes for beads')
